services:
  mitram-touroperator-frontend:
    build: 
      context: ./
      args:
      - REACT_APP_SERVER_URI=/api/ # Example
      dockerfile: Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_PRIMARY_REGION}:mitram-touroperator-frontend
    env_file:
      - ./.env
    container_name: mitram-touroperator-frontend
    networks:
      - touroperator-net
    restart: always 
networks:
  touroperator-net:
    driver: bridge
    external: true