services:
  mitram-touroperator-frontend:
    profiles: ["operator"]
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
       REACT_APP_SERVER_URI: "http://api.mitramtouroperator.tk/api/" # Example
    env_file:
      - ./.env
    environment:
      VIRTUAL_HOST: "mitramtouroperator.tk"
      LETSENCRYPT_HOST: "mitramtouroperator.tk"
      LETSENCRYPT_EMAIL: "roy.cognizant.subhankar623@gmail.com"
    container_name: mitram-touroperator-frontend
    depends_on:
      - mitram-touroperator-backend
    networks:
      - touroperator-net
    restart: always 
networks:
  touroperator-net:
    driver: bridge
    external: true
  