services:
  mitram-touroperator-frontend:
    build: 
      context: ./
      args:
      - REACT_APP_SERVER_URI=http://mitramtourism-backend/api/ # Example
      dockerfile: Dockerfile
    image: 157208622016.dkr.ecr.ap-south-1.amazonaws.com/mitramdocker/mitram-app-hub:mitram-touroperator-frontend-latest
    env_file:
      - ./.env
    container_name: mitram-touroperator-frontend
    networks:
      - touroperator-net
    restart: always 
networks:
  touroperator-net:
    driver: bridge
    external: true