	# Upstreams
    upstream touroperator_frontend {
    server mitram-touroperator-frontend:80;   # container port
    }

    upstream touroperator_backend {
    server mitram-touroperator-backend:5000;  # container port
    }
	
	server {
        listen 81;
		server_name _;
		location / {
			  # The try_files directive handles client-side routing.
              # It attempts to serve the requested URI as a static file, 
              # as a directory, and finally falls back to index.html for React Router to handle.
             #try_files $uri $uri/ /index.html;
			 proxy_pass http://touroperator_frontend;
			 proxy_set_header Host $host;
			 proxy_set_header X-Real-IP $remote_addr;
			 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			 proxy_set_header X-Forwarded-Proto $scheme;
			 # Intercept 404s from the frontend service and serve the root instead
			 proxy_intercept_errors on;
			 error_page 404 =200 /index.html; 
			 # SPA fallback
			 #try_files $uri/ /index.html;
            }
		
        # 2. Route for Node.js Backend
        location /api/ {
		    # Rewrite the URL to remove /api/ before forwarding
		    # The trailing slash in proxy_pass handles path stripping
           	proxy_pass http://touroperator_backend; # Use your Node service name
            proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
        }
		location /.well-known/ {
			return 404;
		}

        # 3. Fix for React Router 404s (on page refresh)
        # If serving static build files directly instead of proxying a dev server:
        # try_files $uri /index.html;
		# Health check endpoint
        location /nginx-health {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }