import  { useEffect, useState, useCallback } from 'react';
import {KeyboardAvoidingView, View, Text, TextInput, ActivityIndicator,
    TouchableOpacity,Platform } from 'react-native';
import * as SecureStore from 'expo-secure-store'; // For storing tokens
import LoginSignUpStyle from '../../styles/loginsignup.js';
import TourCommonStyle from '../../styles/tourCommonStyle.js';

import { useFonts } from 'expo-font';
import { Inter_900Black,Inter_900Black_Italic } from '@expo-google-fonts/inter'; 
import {Poppins_400Regular, Poppins_600SemiBold} from '@expo-google-fonts/poppins';
import {Link,useRouter} from 'expo-router';
import {loginUser,getApiAccessToken,validateTokenWithSession,
  getTokenFromSession,persistDataInCache,getDataFromCache} from '../../admin/admin';
import Ionicons from '@expo/vector-icons/Ionicons';
import AuthCommonModal from '../../admin/authCommonModal.js'
import 'react-native-get-random-values'; // This must precede `uuid`
import { v4 as uuidv4 } from 'uuid';
import * as Linking from 'expo-linking';
import { authorize } from 'react-native-app-auth';
import PleaseWaitScreen from '../../admin/waitscreen.js'
export default function LoginUser(){

  const [email, setEmail] = useState('');
  const [mobile, setMobile] = useState('');
  const [error, setError] = useState('');
   const[modalVisible,setModalVisible] = useState(false);
   const [userProfile,setUserProfile] = useState('');
   const[isLoggedIn,setLoggedIn] = useState(false)
   const [signupEnable,setSignupEnable] = useState(false)
   const [isloading,setIsloading] = useState(false)
   const router = useRouter();
   const redirectUri = Linking.createURL('redirect', {});

  const [fontsLoaded] = useFonts({
      'Inter-Black': Inter_900Black, // Assign a name to the loaded font
      'Poppins-Regular': Poppins_400Regular,
      'Poppins-SemiBold': Poppins_600SemiBold,
      'Inter-Black-Header': Inter_900Black_Italic
    });
  
    // Define your app auth configuration
const config = {
  issuer: 'http://localhost:8080/realms/mitram-dev/protocol/openid-connect/auth',
  clientId: 'confidential',
  redirectUrl: redirectUri, // Use the redirectUri generated by Linking.createURL
  scopes: ['openid', 'profile', 'email', 'offline_access'],
};

 const handleDeepLink = useCallback((url) => {
    // Check if the URL is relevant to the auth flow and process it.
    // react-native-app-auth's internal mechanisms typically manage this
    // without explicit manual parsing if correctly configured.
    console.log('Deep link received:', url);
    // If manual handling is required, you would pass the URL to a specific handler function.
  }, []);


  useEffect(() => {
    // 1. Handle the initial URL (app launched from a closed state)
    Linking.getInitialURL().then((url) => {
      if (url) {
        handleDeepLink(url);
      }
    });

// 2. Handle deep links while the app is already running (foreground/background)
    const subscription = Linking.addEventListener('url', ({ url }) => {
      handleDeepLink(url);
    });

    return () => {
      // Clean up the event listener
      subscription.remove();
    };
  }, [handleDeepLink]);

   // Example authorization function
  const onAuthorize = async () => {
    try {
      // react-native-app-auth will use the configured redirectUrl and listen
      // for the corresponding deep link automatically.
      const result = await authorize(config);
      console.log('Authorization result', result);
    } catch (error) {
      console.error('Authorization error', error);
    }
  };


const handleLogin = async () => {
    setError(''); // Clear previous errors
    
    // Basic validation
    if (!email && !mobile) 
    {
      setError('Please enter both email and mobile.');
      setModalVisible(true);
      return;
    }else{
      setModalVisible(false);
    }
    try {
      setIsloading(true)
     let logintoken = await getApiAccessToken();
        let deviceID = await SecureStore.getItemAsync('appDeviceID');
      if(logintoken && deviceID)
      {
          console.log('token....',logintoken)
          const req_data = {
                        email:email,
                        mobile:mobile,
                         access_token:logintoken
                      };
         // Replace with your actual API call
          const response = await loginUser(req_data);
       if (response) {
        let data = response;
        console.log('data...',data);
        if(response.code === 'NF'|| response.code === 'N')
        {
              setError(response.message);
              setModalVisible(true);
              if(response.code === 'NF')
              {
                setSignupEnable(true);
              }
        }else{
               // Assuming your API returns a token on success
                    await SecureStore.setItemAsync(deviceID, JSON.stringify(data));
              
                router.push({
                        pathname: "/login/validateOTP",
                    params: {  mobile: mobile,email:email}
                    });
                              
      }
      } else {
        setError('Login failed. Please try again.');
        setModalVisible(true);
      }
    }else{
      console.log('No device id or logintoken found')
       setError('Invalid device detected, please try from an android or ios platform');
        setModalVisible(true);
    }
    
    } catch (err) {
      setError('An error occurred. Please check your internet connection.');
    }
  
  }

   useEffect(()=>{
     let mounted = true;
      setModalVisible(false);
      // console.log('useEffect invoked....');
    const timer = setTimeout( () =>{
                
                    const checkIfUserLoggedIn = async () =>{
                       let request_token = await SecureStore.getItemAsync('token');
                       let deviceID = await SecureStore.getItemAsync('appDeviceID');
                      
                       if(!deviceID)
                       {
                            deviceID = uuidv4();
                            await SecureStore.setItemAsync('appDeviceID', deviceID);
                          
                       }
                       
                          console.log('deviceID is ...',deviceID)
                         let result = await SecureStore.getItemAsync(deviceID);
                          
                         if(result && request_token)
                         {
                           // setUserProfile(result);
                           console.log('result email...',email)
                           console.log('result mobile...',mobile)
                          
                          let response = await validateTokenWithSession({access_token: request_token});
                          if(response.isValidRequest === 'Y')
                          {
                           setLoggedIn(true);
                            router.push({
                         pathname: "/login/profile",
                         params: { 
                              email: result.email,
                              mobile: result.mobile,
                              access_token: request_token                         
                           }
                          })
                        }else if(response.isValidRequest === 'N')
                        {
                             setLoggedIn(false);
                        }
                        }
                         else
                        {
                            setLoggedIn(false);
                        }
                                               
                    };
                   if(mounted)
                   {
                     
                      checkIfUserLoggedIn();
                       
                    }
                   }
                  ,100);

                   return () => {
                        mounted = false; // Set flag to false on cleanup
                        clearTimeout(timer); // Clean up the timer
                  };

                  
  },
  []);


  return (
    fontsLoaded ?
    <KeyboardAvoidingView style = {LoginSignUpStyle.centeredContainer}
     behavior={Platform.OS === 'ios' ? 'padding' : undefined}
          keyboardVerticalOffset={Platform.OS === 'ios' ? 64 : 0} // Adjust offset as needed
    
    >
   <Text style={{ fontFamily: 'Inter-Black-Header',
      color:'#f3f3f3d7',fontSize:50 }}>Login</Text>
    <View
      style={LoginSignUpStyle.flexboxcontainer}>
       
       

       <Ionicons name="mail-open" size={24} color="#fcf1f1ff"></Ionicons>


      <TextInput
        style={LoginSignUpStyle.textfieldunderlinedInput}
        placeholder="Email"
        value={email}
        onChangeText={setEmail}
        keyboardType="email-address"
        autoCapitalize="none"
      />
</View>
{
  isloading ?
   
       <PleaseWaitScreen/>:<View/>
    
}
<View>
        {error ?  
        <View>
           <ActivityIndicator 
            size="large" color="#3c3ca7ff"/>
        <AuthCommonModal modalVisible={modalVisible} 
            setModalVisible={setModalVisible} errorMessage={error} setErrorMessage={setError}/>
            </View>
        
        : <View/>}
    </View>

<View
      style={LoginSignUpStyle.flexboxcontainer}>
         <Text style={{fontFamily:'Poppins-Regular',textAlign: 'center'}}>OR</Text>
      </View>
<View
      style={LoginSignUpStyle.flexboxcontainer}>
 <Ionicons name="phone-portrait" size={24} color="white"></Ionicons>
      <TextInput
        style={LoginSignUpStyle.textfieldunderlinedInput}
        placeholder="mobile"
        value={mobile}
        onChangeText={setMobile}
         keyboardType="phone-pad"
        autoCapitalize="none"
      />
    </View>
    <View
      style={LoginSignUpStyle.flexboxcontainer}>
    <View style={LoginSignUpStyle.buttonscontainer}>
    
            <TouchableOpacity 
                    style={LoginSignUpStyle.loginbutton}>
                    <Text style={TourCommonStyle.buttonText} 
                    onPress={handleLogin} >Login</Text>
                  </TouchableOpacity>
       
      {/* Add a "Forgot Password" link or similar */}
    
    </View>

     <View style={LoginSignUpStyle.buttonscontainer}>
         <Link href={{pathname:"/login/signup"}} asChild>
            <TouchableOpacity 
                    style={signupEnable?LoginSignUpStyle.loginbutton:LoginSignUpStyle.disabledButton}>
                    <Text style={TourCommonStyle.buttonText} 
                    
                    >Sign Up</Text>
                  </TouchableOpacity>
    </Link>
    
          
    </View>
    </View>
    
    </KeyboardAvoidingView>:
    <View style={TourCommonStyle.centeredContainer}>
            <ActivityIndicator 
            size="large" color="#3c3ca7ff"/>
            </View>
    
  );

}

