FROM node:20-alpine
RUN rm /etc/nginx/conf.d/default.conf
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# For Create React App (CRA)
# CMD ["npm", "start"]
# For Vite, it might use port 5173, so adjust accordingly
CMD ["npm", "run", "dev"]
