services:
  mitram-tourism-frontend:
    build: 
      context: ./
      args:
      - REACT_APP_SERVER_URI=/api/ # Example
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      VIRTUAL_HOST: "mitramtourism.com"
      LETSENCRYPT_HOST: "mitramtourism.com"
      LETSENCRYPT_EMAIL: "roy.cognizant.subhankar623@gmail.com"
    container_name: mitram-tourism-frontend
    depends_on:
      - mitramtourism-backend
    networks:
      - mitramtourism-net
    restart: always
volumes:
  keycloak_data:
    driver: local
  postgres-data:
    driver: local
networks:
  mitramtourism-net:
    driver: bridge
    external: true
  touroperator-net:
    driver: bridge
    external: true