services:
  mitram-tourism-frontend:
    profiles: ["tourism"]
    build: 
      context: ./
      dockerfile: Dockerfile
      args:
        REACT_APP_SERVER_URI: "http://api.mitramtourism.tk/api/" # Exampleargs:
    env_file:
      - ./.env
    environment:
      VIRTUAL_HOST: "mitramtourism.tk"
      LETSENCRYPT_HOST: "mitramtourism.tk"
      LETSENCRYPT_EMAIL: "roy.cognizant.subhankar623@gmail.com"
    container_name: mitram-tourism-frontend
    depends_on:
      - mitramtourism-backend
    networks:
      - mitramtourism-net
    restart: always
volumes:
  keycloak_data:
    driver: local
  postgres-data:
    driver: local
networks:
  mitramtourism-net:
    driver: bridge
    external: true
  touroperator-net:
    driver: bridge
    external: true