# fly.toml app configuration file generated for mitram-web on 2026-07-19T13:59:13-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mitram-web"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80