services:
  mitram-touroperator-backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
    container_name: mitram-touroperator-backend
    ports:
      - "5000:5000"
    networks:
      - touroperator-net
    restart: always
    command: npm start
networks:
  touroperator-net:
    driver: bridge
    external: true