services:
  mitram-touroperator-backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_PRIMARY_REGION}:mitram-touroperator-backend
    env_file:
      - ./.env
    container_name: mitram-touroperator-backend
    ports:
      - "5000:5000"
    depends_on:
      - mitram-touroperator-frontend
    networks:
      - touroperator-net
    restart: always
    command: npm start
networks:
  touroperator-net:
    driver: bridge
    external: true