# fly.toml app configuration file generated for mitram-nginx-shimmering-branch-4587 on 2026-07-19T14:48:46-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mitram-nginx"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80
