http {

    include /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
	error_log  /var/log/nginx/error.log  warn;
    sendfile        on;

    keepalive_timeout  65;
	 # Use Google DNS or your preferred DNS server
    resolver 127.0.0.11 valid=30s;
    # Include all .conf files from the conf.d directory
    include /etc/nginx/conf.d/*.conf;
	 # Alternatively, use the sites-enabled convention (common in Ubuntu/Debian)
    include /etc/nginx/sites-enabled/*;
    
}