events { worker_connections 1024; }

http {
    server {
        listen 80;

        # 1. Route for React Frontend
        location / {
            proxy_pass http://mitram-web-app:8083/; # Use your React service name
            proxy_set_header Host $host;
        }

        # 2. Route for Node.js Backend
        location /api/ {
		    # Rewrite the URL to remove /api/ before forwarding
		    rewrite ^/api/(.*)$ /$1 break;
            # The trailing slash in proxy_pass handles path stripping
            proxy_pass http://mitramtourism-backend:8090/; # Use your Node service name
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Fix for React Router 404s (on page refresh)
        # If serving static build files directly instead of proxying a dev server:
        # try_files $uri /index.html;
    }
}