name: mitram-app
include:
  - ./tourism-web/docker-compose.dev.yml
  - ./server/docker-compose.dev.yml
  - ./touroperator-frontend/docker-compose.dev.yml
  - ./touroperator-backend/docker-compose.dev.yml
services:
  postgres:
    profiles: ["infra"]
    image: postgres:18
    container_name: postgres_db
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - mitramtourism-net
  keycloak:
    profiles: ["infra"]
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak7
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloakdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HOSTNAME: http://keycloak7:8080
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./server/realm-keycloak.json:/opt/keycloak/data/import/realm-config.json
      - keycloak_data:/opt/keycloak/data/
    command:
      - start-dev
      - --import-realm
      - --http-enabled=true
      - --hostname-strict=false
    networks:
      - mitramtourism-net
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://keycloak7:8080/health/ready
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      - postgres
  nginx:
    profiles: ["proxy"]
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80" 
      - "81:81"
      - "8443:8443"
      - "8444:8444"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
      #- ./mitram-tourism-frontend/build:/var/www/mitram-tourism-frontend/build:ro
     # - ./client/build:/usr/share/nginx/html:ro # Mount built React files
    networks:
      - mitramtourism-net
      - touroperator-net
  letsencrypt:
    profiles: ["proxy"]
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/certs:/etc/nginx/certs
      - /etc/nginx/vhost.d:/etc/nginx/vhost.d
      - /usr/share/nginx/html:/usr/share/nginx/html
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
    networks:
      - mitramtourism-net
      - touroperator-net
  extra-service:
    profiles: ["infra"]
    image: nginx:latest
    container_name: extra_service
    networks:
    - mitramtourism-net
volumes:
  keycloak_data:
    driver: local
  postgres-data:
    driver: local
  teamcity_data:
  teamcity_logs:
networks:
  mitramtourism-net:
    driver: bridge
    external: true
  touroperator-net:
    driver: bridge
    external: true