name: mitram-app

include:
  - ./tourism-web/docker-compose.dev.yml
  - ./server/docker-compose.dev.yml
  - ./touroperator-frontend/docker-compose.dev.yml
  - ./touroperator-backend/docker-compose.dev.yml
services:
  postgres:
    image: postgres:18
    container_name: postgres_db
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - mitramtourism-net
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak7
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloakdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HOSTNAME: http://keycloak7:8080
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./server/realm-keycloak.json:/opt/keycloak/data/import/realm-config.json
      - keycloak_data:/opt/keycloak/data/
    command:
      - start-dev
      - --import-realm
      - --http-enabled=true
      - --hostname-strict=false
    networks:
      - mitramtourism-net
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://keycloak7:8080/health/ready
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      - postgres
  
  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    ports:
      - "80:80" 
      - "81:81"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     # - ./client/build:/usr/share/nginx/html:ro # Mount built React files
    depends_on:
      - mitram-tourism-frontend
      - mitramtourism-backend
      - mitram-touroperator-frontend
      - mitram-touroperator-backend
    command: /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - mitramtourism-net
      - touroperator-net
volumes:
  keycloak_data:
    driver: local
  postgres-data:
    driver: local
networks:
  mitramtourism-net:
    driver: bridge
    external: true
  touroperator-net:
    driver: bridge
    external: true