services:
  mitram-tourism-frontend:
    build: ./tourism-web
    ports:
      - 8083:80
    container_name: mitram-tourism-web
    networks:
      - mitramtourism-net
    environment:
      - REACT_APP_SERVER_URI=http://mitramtourism-backend:8090
    restart: always
  
  postgres:
    image: postgres:18
    container_name: postgres_db
    environment:
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - mitramtourism-net
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak6
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloakdb
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HOSTNAME: http://localhost:8080
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
    ports:
      - 8080:8080
    volumes:
      - ./server/realm-keycloak.json:/opt/keycloak/data/import/realm-config.json
      - keycloak_data:/opt/keycloak/data/
    command:
      - start-dev
      - --import-realm
    networks:
      - mitramtourism-net
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/auth/health/ready
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      - postgres
  
  mitramtourism-backend:
    build: ./server
    container_name: mitramtourism-backend
    environment:
      - OIDC_ISSUER_URL=http://keycloak:8080/realms/mitram-dev
      - OIDC_CLIENT_ID=mitram-tourism-client
    ports:
      - 8090:8090
    depends_on:
      - keycloak
    networks:
      - mitramtourism-net
    restart: always
    command: npm start
  
  nginx:
    image: nginx:alpine
    container_name: nginx_reverse_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mitram-tourism-frontend
      - mitramtourism-backend
    networks:
      - mitramtourism-net
  
volumes:
  keycloak_data:
    driver: local
  postgres-data:
    driver: local
networks:
  mitramtourism-net:
    external: true