apiVersion: apps/v1
kind: Deployment
metadata:
  name: mitram-tourism-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mitram-tourism-backend
  template:
    metadata:
      labels:
        app: mitram-tourism-backend
    spec:
      containers:
      - name: mitram-tourism-backend
        image: 157208622016.dkr.ecr.ap-south-1.amazonaws.com/mitramdocker/mitram-app-hub:mitram-tourism-backend:latest
        ports:
        - containerPort: 8090
