services:
  mitramtourism-backend:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_PRIMARY_REGION}:mitramtourism-backend
    env_file:
      - ./server.env.dev
    container_name: mitramtourism-backend
    ports:
      - "8090:8090"
    depends_on:
      - mitram-tourism-frontend
      - keycloak
    networks:
      - mitramtourism-net
    restart: always
    command: npm start
    
volumes:
  keycloak_data:
    driver: local
  postgres-data:
    driver: local
networks:
  mitramtourism-net:
    driver: bridge
    external: true
  touroperator-net:
    driver: bridge
    external: true