version: '3.8'
services:
   keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak6
    environment:
     - KC_BOOTSTRAP_ADMIN_USERNAME=admin
     - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
     - KC_HOSTNAME_STRICT=false
     - KC_HTTP_ENABLED=true
     - KEYCLOAK_IMPORT=/opt/keycloak/data/import/realm-config.json
    ports:
      - "8080:8080"
    volumes:
      - ./import:/opt/keycloak/data/import
      - keycloak_data:/opt/keycloak/data
    command: ["start-dev", "--import-realm"]
    
    networks:
      - mitramtourism-net
    restart: unless-stopped
  # 3. My Backend Application
   mitramtourism-backend:
    build: ./ # Path to your Dockerfile
    container_name: mitramtourism-backend
    environment:
     - OIDC_ISSUER_URL=http://keycloak:8080/realms/mitram-dev
      # Use internal Docker network name for backend-to-keycloak comms
     - OIDC_CLIENT_ID=mitram-tourism-client
    ports:
      - "8090:8090"
    depends_on:
      - keycloak
    networks:
      - mitramtourism-net
    restart: always
    command: npm start

networks:
  mitramtourism-net:
    driver: bridge
  
volumes:
  keycloak_data: