version: '3.8'
services:
  # 2. Keycloak Service (Version 26+)
   keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak4
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_DEBUG: "true"
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - mitramtourism-net
    restart: always
  # 3. My Backend Application
   mitramtourism-backend:
    build: ./ # Path to your Dockerfile
    container_name: mitramtourism-backend
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      # Use internal Docker network name for backend-to-keycloak comms
      KEYCLOAK_ISSUER: http://keycloak:8080/realms/mitram-dev
    ports:
      - "8090:8090"
    depends_on:
      - keycloak
    networks:
      - mitramtourism-net
    restart: always
    command: npm start

networks:
  mitramtourism-net:
    driver: bridge
  mitramkc-net: 
    driver: bridge 

volumes:
  keycloak_db_data:
  keycloak_data: